<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>Real-value negative selection algorithm</title>
		<link type="text/css" rel="stylesheet" href="style.css"></link>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	</head>
	<body>
		<h1>Real-value negative selection algorithm</h1>
		
		<div id="menu">
			<ul>
				<li><a href="index.php">Index</a></li>
				<li><a href="#settings">Settings</a></li>
				<li><a href="#generations">Detector generations</a></li>
				<li><a href="#tests">Tests</a></li>
				<li><a href="#graphs">Graphs</a></li>
			</ul>
		</div>
		
		<?php require './template/settings.phtml'; ?>

		<table id="generations">
			<caption>Detector generations</caption>
			<thead><tr><th>#</th><th>Elements</th></tr></thead>
			<tbody>
				<?php foreach($generations as $n => $item) { ?>
				<tr>
					<td><?=($n+1)?></td>
					<td>
						<table>
							<thead>
								<tr>
									<th>#</th><th>Centre</th><th>Radius</th>
									<th>Overlap</th><th>Over max</th><th>Score</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($item as $n2 => $item2) { ?>
								<tr>
									<td><?=($n2 + 1)?></td>
									<td><?=$item2->centre->formatted()?></td>
									<td><?=number_format($item2->radius, 3)?></td>
									<td><?=number_format($item2->overlap, 3)?></td>
									<td><?=($item2->overlap > MAX_OVERLAP ? 'yes' : 'no')?></td>
									<td><?=$item2->score?></td>
								</tr>
								<?php } ?>
								<tr>
									<td>Average</td>
									<td><?=$generationStats[$n]['meanCentre']->formatted()?></td>
									<td><?=number_format($generationStats[$n]['meanRadius'], 3)?></td>
									<td><?=number_format($generationStats[$n]['meanOverlap'], 3)?></td>
									<td>–</td>
									<td><?=number_format($generationStats[$n]['meanScore'], 3)?></td>
								</tr>
								<tr>
									<td>St. dev.</td>
									<td><?=$generationStats[$n]['stdevCentre']->formatted()?></td>
									<td><?=number_format($generationStats[$n]['stdevRadius'], 3)?></td>
									<td><?=number_format($generationStats[$n]['stdevOverlap'], 3)?></td>
									<td>–</td>
									<td><?=number_format($generationStats[$n]['stdevScore'], 3)?></td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>

		<table id="tests">
			<caption>Tests</caption>
			<thead><tr>
				<th>#</th><th>Antigen</th><th>Result</th><th>Generation #</th><th>Detector #</th>
			</tr></thead>
			<tbody>
				<?php foreach($tests as $n => $item) { ?>
				<tr>
					<td><?=($n + 1)?></td>
					<td><?=$item['antigen']?></td>
					<td><?=($item['result'] ? 'Alarm!' : 'OK')?></td>
					<td><?=$item['generation']?></td>
					<td><?=$item['detector_n']?></td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
		
		<p>Run time: <?=$runTime[0]?> s main,
			<?=$runTime[1]?> s with stats,
			<?=$runTime[2]?> s total.</p>
		<p>Memory: <?=$memory[0]?> KB main,
			<?=$memory[1]?> KB after stats,
			<?=$memory[2]?> KB final.</p>
		
		<h2 id="graphs">Graphs</h2>
		<p>Legend:</p>
		<ul>
			<li>Blue circle with centre dot: detector</li>
			<li>Green dot: self</li>
			<li>Red dot: antigen</li>
			<li>Yellow dot: non-harmful antigen</li>
		</ul>
		<?php for($i = 0; $i < DIMENSIONS - 1; $i++) { ?>
			<p><br />x: <?=$space[$i]['desc']?>; y: <?=$space[$i + 1]['desc']?></p>
			<img src="graph.php?<?=http_build_query(array('dimensions' => array($i, $i + 1)))?>" />
		<?php } ?>
	</body>
</html>