CREATE TABLE `runs` (
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`date_created` DATETIME NOT NULL,
`pad_detectors` TINYINT(1) NOT NULL DEFAULT '0',
`max_variation` FLOAT (11,3) NOT NULL DEFAULT '0',
`max_overlap` FLOAT (11,3) NOT NULL DEFAULT '0',
`dimensions` INT UNSIGNED NOT NULL DEFAULT '0',
`max_population` INT UNSIGNED NOT NULL DEFAULT '0',
`max_radius` FLOAT (11,3) NOT NULL DEFAULT '0',
`max_tests` INT UNSIGNED NOT NULL DEFAULT '0',
`next_gen_after` INT UNSIGNED NOT NULL DEFAULT '0',
`top_toclone` INT UNSIGNED NOT NULL DEFAULT '0',
`detector_sortfield` VARCHAR(255) NOT NULL DEFAULT '',
`max_dim` INT UNSIGNED NOT NULL DEFAULT '0',
`autoradius` TINYINT(1) NOT NULL DEFAULT '0',
`start_padding` TINYINT(1) NOT NULL DEFAULT '0',
`runtime` FLOAT (20,15) NOT NULL DEFAULT '0',
`finished` TINYINT(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `dimensions` (
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`run_id` INT UNSIGNED NOT NULL DEFAULT '0',
`min` FLOAT (11,3) NOT NULL DEFAULT '0',
`max` FLOAT (11,3) NOT NULL DEFAULT '0',
`description` VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `points` (
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`run_id` INT UNSIGNED NOT NULL DEFAULT '0',
`type` ENUM('self', 'antigen', 'detector') NOT NULL DEFAULT 'antigen'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `point_dimensions` (
`point_id` INT UNSIGNED NOT NULL DEFAULT '0',
`dimension_id` INT UNSIGNED NOT NULL DEFAULT '0',
`value` FLOAT (11,3) NOT NULL DEFAULT '0'
);

CREATE TABLE `detectors` (
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`run_id` INT UNSIGNED NOT NULL DEFAULT '0',
`generation` INT UNSIGNED NOT NULL DEFAULT '0',
`parent_id` INT UNSIGNED NOT NULL DEFAULT '0',
`centre_point_id` INT UNSIGNED NOT NULL DEFAULT '0',
`radius` FLOAT (11,3) NOT NULL DEFAULT '0',
`score` INT UNSIGNED NOT NULL DEFAULT '0',
`overlap` FLOAT (11,3) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tests` (
`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`run_id` INT UNSIGNED NOT NULL DEFAULT '0',
`antigen_point_id` INT UNSIGNED NOT NULL DEFAULT '0',
`result` TINYINT(1) NOT NULL DEFAULT '0',
`generation` INT UNSIGNED NOT NULL DEFAULT '0',
`detector_id` INT UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;